# Etapa de construcción
FROM node:18 AS build
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

# Etapa de producción con nginx
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html

# Copiamos la configuración de nginx (asegúrate de que este archivo exista)
COPY nginx.conf /etc/nginx/nginx.conf

# Expone el puerto 80 para acceso externo
EXPOSE 80

# Inicia nginx en primer plano
CMD ["nginx", "-g", "daemon off;"]
